Added instructions for audio transcoding
Irrational-Encoding-Wizardry/guide.encode.moe pull request #24
Opened 2019-07-10 02:00 UTC by rokweom

I know that @LightArrowsEXE already wrote this, but his instructions are not in line with what was written on the "Preparation and Necessary Software" site (using ffmpeg flac instead of libflac), he repeated a lot of things already written in the aforementioned site, and also added a lot of information that are completely unnecessary, like explaining the difference between lossy and lossless (basic knowledge that is IMO not needed in this guide, plus it's also mentioned in "Preparation and Necessary Software")  or comparing file sizes for different flac levels, or explaining what "FLAC" means, lol. I also disagree with some of his statements, which I commented in his pool request.

2019-07-10 04:12 UTC, Doarom commented
I would suggest running flac with `-V` just to be safe.

2019-07-10 05:05 UTC, Doarom commented
Also it would be pretty nice to expand on multichannel files a bit because certain channel layouts will fail to encode with the current examples.

2019-11-04 23:56 UTC, FichteFoll requested changes
Sorry it took so long to review this. I started reviewing this months ago but somehow didn't end up finishing it and then it got buried in my open tabs and lack of time, which I'm now trying to catch up on.

---

Please separate all code blocks from text with a blank line.

For semantic line feeds, it is very rare to not have a line break after a comma and usually only for small enumerations or the likes of "Additionally,", whose proper name I forgot. Some sentences in here have odd line breaks.

2019-11-04 23:56 UTC, FichteFoll commented on encoding/basics-and-workflow.md
> +But, for the ease of use, we suggest adding them to PATH,
I'm not on top of the entire guide's contents, but is "adding to PATH" explained anywhere? Or maybe we can add a glossary entry for an all-caps PATH with explanations without having to repeat or reference this all the time?

2019-11-04 23:56 UTC, FichteFoll commented on encoding/basics-and-workflow.md
> +Basic ffmpeg usage is very simple—you just need to specify the input file,
No comma here.

2019-11-04 23:56 UTC, FichteFoll commented on encoding/basics-and-workflow.md
> +but there is a faster and more convinient way to do that—piping.
```suggestion
but there is a faster and more convenient way to do that: piping.
```

2019-11-04 23:56 UTC, FichteFoll commented on encoding/basics-and-workflow.md
> +With this option FLAC will ignore the header
```suggestion
With this option, FLAC will ignore the header
```

2019-11-04 23:56 UTC, FichteFoll commented on encoding/basics-and-workflow.md
> +ffmpeg -i "input.dts" -acodec pcm_s24le -f wav -| flac -8 --ignore-chunk-sizes - -o "output.flac"
24bit flac is padded to 32 bits per sample, which means 25% of the resulting file contain no information. Encoding dts to wav 24-bit seems reasonable, but at this point we should definitely mention this fallacy with flac. See also #2.

2019-11-04 23:56 UTC, FichteFoll commented on encoding/basics-and-workflow.md
> +* go to [qaac's download page][qaac] and download the newest build
Add a blank line around lists.

2019-11-04 23:56 UTC, FichteFoll commented on encoding/basics-and-workflow.md
> +(at the time of writing, `qaac_2.68.zip`) and the `makeportable.zip` file
Indent subsequent lines of a list item.

2019-11-04 23:56 UTC, FichteFoll commented on encoding/basics-and-workflow.md
> +then extract contents of `makeportable.zip` to it
This should be another step, shouldn't it.

Also, this should in general be an ordered list. Use `1.` for every item.

2019-11-04 23:56 UTC, FichteFoll commented on encoding/basics-and-workflow.md
> +* done, you can now delete the iTunes installation file.
All items in this list should be proper sentences.

2019-11-04 23:56 UTC, FichteFoll commented on encoding/basics-and-workflow.md
> +opusenc CLI uses bitrate control,
I don't think there should be a comma here?

2019-11-04 23:56 UTC, FichteFoll commented on encoding/basics-and-workflow.md
> +insted of some kind constant quality mode, like in qaac.
```suggestion
instead of some kind constant quality mode, like in qaac.
```

2019-11-04 23:56 UTC, FichteFoll commented on encoding/basics-and-workflow.md
> +This doesn't mean it works in constant bitrate mode—[the target bitrate is calibrated against the internal constant quality targets
That's a really long link text. Please try to rephrase this.

2019-11-04 23:56 UTC, FichteFoll commented on encoding/basics-and-workflow.md
> +a little bit funky—you will have to set different bitrate for stereo and for multichannel files.
```suggestion
a little bit funky. 
You will have to set different bitrate for stereo and for multichannel files.
```

A period here is fine.

2019-11-04 23:56 UTC, FichteFoll commented on encoding/basics-and-workflow.md
> +while for 5.1 something in the neighbourhood of 320-384 kbps should be OK.
```suggestion
while for 5.1 something in the range of 320-384 kbps should be OK.  
```

If the two spaces at the end of the line are intended, use `<br>` to add a line break instead. Those are resistent to removal of trailing whitespace.

2020-09-14 03:22 UTC, anonyno commented
i can help

2020-09-25 19:23 UTC, anonyno commented
here #62

2023-02-12 13:50 UTC, FichteFoll commented
Superseded by #62 (which has been merged).

2023-02-12 13:50 UTC, closed without merging